/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    leads: Lead;
    config: Config1;
    users: User;
    media: Media;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    leads: LeadsSelect<false> | LeadsSelect<true>;
    config: ConfigSelect<false> | ConfigSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Liste des leads générés par le site
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name?: string | null;
  phone?: string | null;
  email?: string | null;
  adress?: string | null;
  message?: string | null;
  step1?: string | null;
  step2?: string | null;
  step3?: string | null;
  step4?: string | null;
  consentMain?: boolean | null;
  consentPartners?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Configuration globale du site – titres, images, contacts, section À propos etc.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "config".
 */
export interface Config1 {
  id: number;
  /**
   * Numéro de téléphone affiché dans l’en-tête / le footer
   */
  phone?: string | null;
  /**
   * Adresse email visible pour les utilisateurs
   */
  email: string;
  /**
   * Image de fond de la section héroïque
   */
  hero_image: number | Media;
  /**
   * Texte superposé sur l’image principale
   */
  hero_image_label?: {
    /**
     * Texte principal affiché sur le badge de l’image Hero
     */
    hero_image_label_1?: string | null;
    /**
     * Texte secondaire affiché sous le texte principal du badge
     */
    hero_image_label_2?: string | null;
  };
  /**
   * Utiliser uniquement le **gras** pour mettre en valeur des mots
   */
  main_title: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Petit texte affiché sous le titre principal
   */
  sub_main_title?: string | null;
  /**
   * Texte des 3 tags affichés sous le titre principal
   */
  main_tags?: {
    /**
     * Première étiquette
     */
    main_tag_1?: string | null;
    /**
     * Deuxième étiquette
     */
    main_tag_2?: string | null;
    /**
     * Troisième étiquette
     */
    main_tag_3?: string | null;
  };
  /**
   * Texte et option du(s) bouton(s) dans la Hero
   */
  main_button: {
    /**
     * Libellé du premier bouton
     */
    main_button_1?: string | null;
    /**
     * Libellé du second bouton
     */
    main_button_2?: string | null;
    /**
     * Fichier PDF à télécharger via le bouton
     */
    guide_pdf: number | Media;
    /**
     * Fichier PDF à télécharger via le bouton
     */
    doc_pdf?: (number | null) | Media;
  };
  /**
   * Titre de la section À propos
   */
  about_title?: string | null;
  /**
   * Texte ou paragraphe présentant le site ou l’entreprise
   */
  about_text?: string | null;
  /**
   * Quatre services présentés avec titre + description
   */
  about_features: {
    /**
     * Premier service détaillé
     */
    about_feature_1: {
      /**
       * Titre de ce service
       */
      about_feature_title_1: string;
      /**
       * Description détaillée du service
       */
      about_feature_text_1: string;
    };
    /**
     * Deuxième service détaillé
     */
    about_feature_2: {
      /**
       * Titre de ce service
       */
      about_feature_title_2: string;
      /**
       * Description détaillée du service
       */
      about_feature_text_2: string;
    };
    /**
     * Troisième service détaillé
     */
    about_feature_3: {
      /**
       * Titre de ce service
       */
      about_feature_title_3: string;
      /**
       * Description détaillée du service
       */
      about_feature_text_3: string;
    };
    /**
     * Quatrième service détaillé
     */
    about_feature_4: {
      /**
       * Titre de ce service
       */
      about_feature_title_4: string;
      /**
       * Description détaillée du service
       */
      about_feature_text_4: string;
    };
  };
  /**
   * Image utilisée pour illustrer la section À Propos
   */
  about_image?: (number | null) | Media;
  /**
   * Bloc complet : titre + paragraphes + image + avantages
   */
  about_section: {
    /**
     * Titre principal de cette section
     */
    about_heading: string;
    /**
     * Textes explicatifs de la section
     */
    about_paragraphs?: {
      /**
       * Premier paragraphe
       */
      para_1?: string | null;
      /**
       * Deuxième paragraphe
       */
      para_2?: string | null;
      /**
       * Troisième paragraphe
       */
      para_3?: string | null;
    };
  };
  /**
   * Image(s) avant / après pour démontrer les transformations
   */
  caroussel_section?:
    | {
        /**
         * Image illustrant un chantier avant modifications
         */
        before?: (number | null) | Media;
        /**
         * Image illustrant le chantier après modifications
         */
        after?: (number | null) | Media;
        /**
         * Titre pour ce couple avant/après
         */
        title: string;
        /**
         * Texte explicatif de ce qu’on voit sur les images
         */
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Liste des avis / témoignages des clients
   */
  testimonials_section?:
    | {
        /**
         * Nom du client ou témoin
         */
        title?: string | null;
        /**
         * Âge du client (optionnel)
         */
        age?: string | null;
        /**
         * Contenu du témoignage
         */
        text?: string | null;
        /**
         * Ville, région ou lieu du client
         */
        location?: string | null;
        /**
         * Note donnée par le client, entier de 1 à 5. Laisser vide si inconnue.
         */
        rating?: number | null;
        date?: string | null;
        source?: ('direct' | 'google') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Présentation des services offerts
   */
  services_section?: {
    /**
     * Titre pour la section des services
     */
    title?: string | null;
    /**
     * Texte introductif des services
     */
    description?: string | null;
    /**
     * Détail du 1ᵉʳ service
     */
    about_feature_1?: {
      /**
       * Nom du service
       */
      about_feature_title_1?: string | null;
      /**
       * Description du service
       */
      about_feature_text_1?: string | null;
    };
    /**
     * Détail du 2ᵉ service
     */
    about_feature_2?: {
      /**
       * Nom du service
       */
      about_feature_title_2?: string | null;
      /**
       * Description du service
       */
      about_feature_text_2?: string | null;
    };
    /**
     * Détail du 3ᵉ service
     */
    about_feature_3?: {
      /**
       * Nom du service
       */
      about_feature_title_3?: string | null;
      /**
       * Description du service
       */
      about_feature_text_3?: string | null;
    };
    /**
     * Détail du 4ᵉ service
     */
    about_feature_4?: {
      /**
       * Nom du service
       */
      about_feature_title_4?: string | null;
      /**
       * Description du service
       */
      about_feature_text_4?: string | null;
    };
    /**
     * Détail du 5ᵉ service
     */
    about_feature_5?: {
      /**
       * Nom du service
       */
      about_feature_title_5?: string | null;
      /**
       * Description du service
       */
      about_feature_text_5?: string | null;
    };
    /**
     * Détail du 6ᵉ service
     */
    about_feature_6?: {
      /**
       * Nom du service
       */
      about_feature_title_6?: string | null;
      /**
       * Description du service
       */
      about_feature_text_6?: string | null;
    };
  };
  /**
   * Infos sur les aides ou financement possibles
   */
  financial_section?: {
    /**
     * Titre de la section financement
     */
    title?: string | null;
    /**
     * Texte de description générale du financement
     */
    description?: string | null;
    /**
     * Texte secondaire ou complémentaire
     */
    sub_description?: string | null;
    /**
     * Premier détail d’aide financière
     */
    financial_help_1?: {
      /**
       * Texte sur la bulle/icône
       */
      icon_text?: string | null;
      /**
       * Titre de cette aide
       */
      title?: string | null;
      /**
       * Détails de cette aide
       */
      description?: string | null;
      /**
       * Fichier PDF à télécharger via le bouton
       */
      impot_pdf?: (number | null) | Media;
    };
    /**
     * Deuxième aide détaillée
     */
    financial_help_2?: {
      /**
       * Texte sur l’icône
       */
      icon_text?: string | null;
      /**
       * Titre de cette aide
       */
      title?: string | null;
      /**
       * Détails de cette aide
       */
      description?: string | null;
    };
    /**
     * Troisième aide détaillée
     */
    financial_help_3?: {
      /**
       * Texte sur l’icône
       */
      icon_text?: string | null;
      /**
       * Titre de cette aide
       */
      title?: string | null;
      /**
       * Détails de cette aide
       */
      description?: string | null;
    };
    /**
     * Quatrième aide détaillée
     */
    financial_help_4?: {
      /**
       * Texte sur l’icône
       */
      icon_text?: string | null;
      /**
       * Titre de cette aide
       */
      title?: string | null;
      /**
       * Détails de cette aide
       */
      description?: string | null;
    };
  };
  /**
   * Champs pour configurer le formulaire de contact
   */
  form_section?: {
    /**
     * Titre du formulaire
     */
    title?: string | null;
    /**
     * Texte explicatif du formulaire
     */
    description?: string | null;
    /**
     * Texte indiquant la disponibilité (ex : horaires)
     */
    disponibility?: string | null;
    /**
     * Définition de la zone géographique d’intervention
     */
    work_zone?: {
      /**
       * Titre du bloc zone
       */
      title?: string | null;
      /**
       * Nom de la région d’intervention
       */
      region?: string | null;
      /**
       * Rayon autour de la région (km par ex.)
       */
      radius?: string | null;
    };
    /**
     * Délais estimés pour devis + travaux + total
     */
    time_section?: {
      /**
       * Titre du bloc temporal
       */
      title?: string | null;
      /**
       * Durées pour chaque étape
       */
      list?: {
        /**
         * Temps estimé pour fournir le devis
         */
        devis?: string | null;
        /**
         * Durée estimée des travaux
         */
        travaux?: string | null;
        /**
         * Somme des délais devis + travaux
         */
        total?: string | null;
      };
    };
  };
  /**
   * Champs pour configurer la partie FAQ
   */
  faq_section?: {
    title?: string | null;
    description?: string | null;
    faq?:
      | {
          question?: string | null;
          answer?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  footer_section?: {
    title?: string | null;
    description?: string | null;
    region?: string | null;
  };
  /**
   * Informations légales de l'entreprise, reprises dans les données structurées du site
   */
  legal_section?: {
    legal_name?: string | null;
    legal_form?: string | null;
    siren?: string | null;
    street_address?: string | null;
    postal_code?: string | null;
    locality?: string | null;
  };
  /**
   * Note moyenne de la fiche Google, telle qu'affichée sur Google. Laisser vide si inconnue.
   */
  google_rating?: number | null;
  /**
   * Nombre d'avis de la fiche Google, tel qu'affiché sur Google.
   */
  google_review_count?: number | null;
  /**
   * Adresse https de la fiche Google, pour que la note soit vérifiable.
   */
  google_profile_url?: string | null;
  /**
   * Liens affichés dans le menu déroulant Services
   */
  menu_services?:
    | {
        label: string;
        href: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Description courte de l'image, lue par les lecteurs d'écran
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * Pages du site : villes, départements, services
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Partie finale de l'URL, par exemple douche-senior-blois
   */
  slug: string;
  /**
   * Utilisé dans le fil d'Ariane et les liens vers cette page
   */
  navLabel: string;
  pageType: 'city' | 'department' | 'service' | 'legal';
  parent?: (number | null) | Page;
  /**
   * Nom de la ville ou du département, repris dans les données structurées
   */
  areaName?: string | null;
  departmentCode?: string | null;
  seo: {
    title: string;
    description: string;
    /**
     * Image 1200 x 630, remplacée par l'image par défaut si vide
     */
    image?: (number | null) | Media;
  };
  layout: (
    | HeroBlock
    | FeatureCardsBlock
    | ZoneListBlock
    | TestimonialBlock
    | ServiceCardsBlock
    | AidCardsBlock
    | StepsBlock
    | LinkCardsBlock
    | CtaBlock
  )[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  /**
   * Ligne affichée avec un repère au dessus du titre (villes)
   */
  location?: string | null;
  titleBefore: string;
  titleHighlight: string;
  titleAfter?: string | null;
  intro: string;
  ctaLabel: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureCardsBlock".
 */
export interface FeatureCardsBlock {
  background: 'default' | 'muted';
  heading?: string | null;
  intro?: string | null;
  layout: 'centered' | 'left' | 'inline';
  columns: '1' | '2' | '3' | '4';
  cards: {
    icon: 'none' | 'mapPin' | 'clock' | 'shield' | 'euro' | 'checkCircle' | 'fileText';
    title: string;
    text: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'featureCards';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ZoneListBlock".
 */
export interface ZoneListBlock {
  background: 'default' | 'muted';
  heading: string;
  showMapIcon?: boolean | null;
  columns?: ('4' | '5') | null;
  intro?: string | null;
  items: {
    name: string;
    id?: string | null;
  }[];
  outro?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'zoneList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialBlock".
 */
export interface TestimonialBlock {
  background: 'default' | 'muted';
  quote: string;
  author: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonial';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServiceCardsBlock".
 */
export interface ServiceCardsBlock {
  background: 'default' | 'muted';
  heading: string;
  columns: '2' | '3';
  cards: {
    title: string;
    description?: string | null;
    bullets?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    linkLabel?: string | null;
    linkHref?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'serviceCards';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AidCardsBlock".
 */
export interface AidCardsBlock {
  background: 'default' | 'muted';
  variant?: ('compact' | 'detailed') | null;
  heading: string;
  intro?: string | null;
  cards?:
    | {
        icon: 'none' | 'mapPin' | 'clock' | 'shield' | 'euro' | 'checkCircle' | 'fileText';
        title: string;
        text: string;
        highlight?: string | null;
        details?:
          | {
              label: string;
              text: string;
              id?: string | null;
            }[]
          | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  buttonLabel?: string | null;
  buttonHref?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'aidCards';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StepsBlock".
 */
export interface StepsBlock {
  background: 'default' | 'muted';
  heading: string;
  withCards?: boolean | null;
  items: {
    title: string;
    text: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'steps';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LinkCardsBlock".
 */
export interface LinkCardsBlock {
  background: 'default' | 'muted';
  heading: string;
  intro?: string | null;
  links: {
    label: string;
    description: string;
    href: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'linkCards';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock".
 */
export interface CtaBlock {
  heading: string;
  text: string;
  ctaLabel: string;
  /**
   * Laisser vide pour afficher le numéro de téléphone
   */
  phoneLabel?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'config';
        value: number | Config1;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  adress?: T;
  message?: T;
  step1?: T;
  step2?: T;
  step3?: T;
  step4?: T;
  consentMain?: T;
  consentPartners?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "config_select".
 */
export interface ConfigSelect<T extends boolean = true> {
  phone?: T;
  email?: T;
  hero_image?: T;
  hero_image_label?:
    | T
    | {
        hero_image_label_1?: T;
        hero_image_label_2?: T;
      };
  main_title?: T;
  sub_main_title?: T;
  main_tags?:
    | T
    | {
        main_tag_1?: T;
        main_tag_2?: T;
        main_tag_3?: T;
      };
  main_button?:
    | T
    | {
        main_button_1?: T;
        main_button_2?: T;
        guide_pdf?: T;
        doc_pdf?: T;
      };
  about_title?: T;
  about_text?: T;
  about_features?:
    | T
    | {
        about_feature_1?:
          | T
          | {
              about_feature_title_1?: T;
              about_feature_text_1?: T;
            };
        about_feature_2?:
          | T
          | {
              about_feature_title_2?: T;
              about_feature_text_2?: T;
            };
        about_feature_3?:
          | T
          | {
              about_feature_title_3?: T;
              about_feature_text_3?: T;
            };
        about_feature_4?:
          | T
          | {
              about_feature_title_4?: T;
              about_feature_text_4?: T;
            };
      };
  about_image?: T;
  about_section?:
    | T
    | {
        about_heading?: T;
        about_paragraphs?:
          | T
          | {
              para_1?: T;
              para_2?: T;
              para_3?: T;
            };
      };
  caroussel_section?:
    | T
    | {
        before?: T;
        after?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  testimonials_section?:
    | T
    | {
        title?: T;
        age?: T;
        text?: T;
        location?: T;
        rating?: T;
        date?: T;
        source?: T;
        id?: T;
      };
  services_section?:
    | T
    | {
        title?: T;
        description?: T;
        about_feature_1?:
          | T
          | {
              about_feature_title_1?: T;
              about_feature_text_1?: T;
            };
        about_feature_2?:
          | T
          | {
              about_feature_title_2?: T;
              about_feature_text_2?: T;
            };
        about_feature_3?:
          | T
          | {
              about_feature_title_3?: T;
              about_feature_text_3?: T;
            };
        about_feature_4?:
          | T
          | {
              about_feature_title_4?: T;
              about_feature_text_4?: T;
            };
        about_feature_5?:
          | T
          | {
              about_feature_title_5?: T;
              about_feature_text_5?: T;
            };
        about_feature_6?:
          | T
          | {
              about_feature_title_6?: T;
              about_feature_text_6?: T;
            };
      };
  financial_section?:
    | T
    | {
        title?: T;
        description?: T;
        sub_description?: T;
        financial_help_1?:
          | T
          | {
              icon_text?: T;
              title?: T;
              description?: T;
              impot_pdf?: T;
            };
        financial_help_2?:
          | T
          | {
              icon_text?: T;
              title?: T;
              description?: T;
            };
        financial_help_3?:
          | T
          | {
              icon_text?: T;
              title?: T;
              description?: T;
            };
        financial_help_4?:
          | T
          | {
              icon_text?: T;
              title?: T;
              description?: T;
            };
      };
  form_section?:
    | T
    | {
        title?: T;
        description?: T;
        disponibility?: T;
        work_zone?:
          | T
          | {
              title?: T;
              region?: T;
              radius?: T;
            };
        time_section?:
          | T
          | {
              title?: T;
              list?:
                | T
                | {
                    devis?: T;
                    travaux?: T;
                    total?: T;
                  };
            };
      };
  faq_section?:
    | T
    | {
        title?: T;
        description?: T;
        faq?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  footer_section?:
    | T
    | {
        title?: T;
        description?: T;
        region?: T;
      };
  legal_section?:
    | T
    | {
        legal_name?: T;
        legal_form?: T;
        siren?: T;
        street_address?: T;
        postal_code?: T;
        locality?: T;
      };
  google_rating?: T;
  google_review_count?: T;
  google_profile_url?: T;
  menu_services?:
    | T
    | {
        label?: T;
        href?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?: T | {};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  slug?: T;
  navLabel?: T;
  pageType?: T;
  parent?: T;
  areaName?: T;
  departmentCode?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        featureCards?: T | FeatureCardsBlockSelect<T>;
        zoneList?: T | ZoneListBlockSelect<T>;
        testimonial?: T | TestimonialBlockSelect<T>;
        serviceCards?: T | ServiceCardsBlockSelect<T>;
        aidCards?: T | AidCardsBlockSelect<T>;
        steps?: T | StepsBlockSelect<T>;
        linkCards?: T | LinkCardsBlockSelect<T>;
        cta?: T | CtaBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  location?: T;
  titleBefore?: T;
  titleHighlight?: T;
  titleAfter?: T;
  intro?: T;
  ctaLabel?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureCardsBlock_select".
 */
export interface FeatureCardsBlockSelect<T extends boolean = true> {
  background?: T;
  heading?: T;
  intro?: T;
  layout?: T;
  columns?: T;
  cards?:
    | T
    | {
        icon?: T;
        title?: T;
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ZoneListBlock_select".
 */
export interface ZoneListBlockSelect<T extends boolean = true> {
  background?: T;
  heading?: T;
  showMapIcon?: T;
  columns?: T;
  intro?: T;
  items?:
    | T
    | {
        name?: T;
        id?: T;
      };
  outro?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialBlock_select".
 */
export interface TestimonialBlockSelect<T extends boolean = true> {
  background?: T;
  quote?: T;
  author?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServiceCardsBlock_select".
 */
export interface ServiceCardsBlockSelect<T extends boolean = true> {
  background?: T;
  heading?: T;
  columns?: T;
  cards?:
    | T
    | {
        title?: T;
        description?: T;
        bullets?:
          | T
          | {
              text?: T;
              id?: T;
            };
        linkLabel?: T;
        linkHref?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AidCardsBlock_select".
 */
export interface AidCardsBlockSelect<T extends boolean = true> {
  background?: T;
  variant?: T;
  heading?: T;
  intro?: T;
  cards?:
    | T
    | {
        icon?: T;
        title?: T;
        text?: T;
        highlight?: T;
        details?:
          | T
          | {
              label?: T;
              text?: T;
              id?: T;
            };
        note?: T;
        id?: T;
      };
  buttonLabel?: T;
  buttonHref?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StepsBlock_select".
 */
export interface StepsBlockSelect<T extends boolean = true> {
  background?: T;
  heading?: T;
  withCards?: T;
  items?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LinkCardsBlock_select".
 */
export interface LinkCardsBlockSelect<T extends boolean = true> {
  background?: T;
  heading?: T;
  intro?: T;
  links?:
    | T
    | {
        label?: T;
        description?: T;
        href?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock_select".
 */
export interface CtaBlockSelect<T extends boolean = true> {
  heading?: T;
  text?: T;
  ctaLabel?: T;
  phoneLabel?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}