/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    config: Config1;
    media: Media;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    config: ConfigSelect<false> | ConfigSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * Configuration globale du site – titres, images, contacts, section À propos etc.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "config".
 */
export interface Config1 {
  id: number;
  /**
   * Numéro de téléphone affiché dans l’en-tête / footer
   */
  phone?: string | null;
  /**
   * Adresse email visible pour les utilisateurs
   */
  email: string;
  /**
   * Image de fond de la section héroïque
   */
  hero_image: number | Media;
  /**
   * Texte superposé sur l’image principale
   */
  hero_image_label?: {
    hero_image_label_1?: string | null;
    hero_image_label_2?: string | null;
  };
  /**
   * Utiliser uniquement le gras pour mettre en valeur des mots
   */
  main_title: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Petit texte affiché sous le titre principal
   */
  sub_main_title?: string | null;
  /**
   * Texte pour les 3 tags affichés sous le titre
   */
  main_tags?: {
    main_tag_1?: string | null;
    main_tag_2?: string | null;
    main_tag_3?: string | null;
  };
  /**
   * Texte des deux boutons principaux visible dans la Hero
   */
  main_button: {
    main_button_1?: string | null;
    main_button_2?: string | null;
    guide_pdf: number | Media;
  };
  /**
   * Titre de la section À propos du site
   */
  about_title?: string | null;
  /**
   * Paragraphe ou contenu riche (gras autorisé si nécessaire)
   */
  about_text?: string | null;
  /**
   * 4 services que vous offrez — titre + description pour chacun
   */
  about_features: {
    about_feature_1: {
      about_feature_title_1: string;
      about_feature_text_1: string;
    };
    about_feature_2: {
      about_feature_title_2: string;
      about_feature_text_2: string;
    };
    about_feature_3: {
      about_feature_title_3: string;
      about_feature_text_3: string;
    };
    about_feature_4: {
      about_feature_title_4: string;
      about_feature_text_4: string;
    };
  };
  /**
   * Image illustratrice pour la section À Propos
   */
  about_image?: (number | null) | Media;
  /**
   * Titre + texte explicatif + image + avantages (liste)
   */
  about_section: {
    about_heading: string;
    about_paragraphs?: {
      para_1?: string | null;
      para_2?: string | null;
      para_3?: string | null;
    };
  };
  caroussel_section?:
    | {
        /**
         * Image illustratrice d'un chantier avant changements
         */
        before?: (number | null) | Media;
        /**
         * Image illustratrice d'un chantier apres changements
         */
        after?: (number | null) | Media;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  testimonials_section?:
    | {
        title?: string | null;
        age?: string | null;
        text?: string | null;
        location?: string | null;
        id?: string | null;
      }[]
    | null;
  services_section?: {
    title?: string | null;
    description?: string | null;
    about_feature_1?: {
      about_feature_title_1?: string | null;
      about_feature_text_1?: string | null;
    };
    about_feature_2?: {
      about_feature_title_2?: string | null;
      about_feature_text_2?: string | null;
    };
    about_feature_3?: {
      about_feature_title_3?: string | null;
      about_feature_text_3?: string | null;
    };
    about_feature_4?: {
      about_feature_title_4?: string | null;
      about_feature_text_4?: string | null;
    };
    about_feature_5?: {
      about_feature_title_5?: string | null;
      about_feature_text_5?: string | null;
    };
    about_feature_6?: {
      about_feature_title_6?: string | null;
      about_feature_text_6?: string | null;
    };
  };
  financial_section?: {
    title?: string | null;
    description?: string | null;
    sub_descrition?: string | null;
    financial_help_1?: {
      icon_text?: string | null;
      title?: string | null;
      description?: string | null;
    };
    financial_help_2?: {
      icon_text?: string | null;
      title?: string | null;
      description?: string | null;
    };
    financial_help_3?: {
      icon_text?: string | null;
      title?: string | null;
      description?: string | null;
    };
    financial_help_4?: {
      icon_text?: string | null;
      title?: string | null;
      description?: string | null;
    };
  };
  form_section?: {
    title?: string | null;
    description?: string | null;
    work_zone?: {
      title?: string | null;
      region?: string | null;
      radius?: string | null;
    };
    time_section?: {
      title?: string | null;
      list?: {
        devis?: string | null;
        travaux?: string | null;
        total?: string | null;
      };
    };
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'config';
        value: number | Config1;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "config_select".
 */
export interface ConfigSelect<T extends boolean = true> {
  phone?: T;
  email?: T;
  hero_image?: T;
  hero_image_label?:
    | T
    | {
        hero_image_label_1?: T;
        hero_image_label_2?: T;
      };
  main_title?: T;
  sub_main_title?: T;
  main_tags?:
    | T
    | {
        main_tag_1?: T;
        main_tag_2?: T;
        main_tag_3?: T;
      };
  main_button?:
    | T
    | {
        main_button_1?: T;
        main_button_2?: T;
        guide_pdf?: T;
      };
  about_title?: T;
  about_text?: T;
  about_features?:
    | T
    | {
        about_feature_1?:
          | T
          | {
              about_feature_title_1?: T;
              about_feature_text_1?: T;
            };
        about_feature_2?:
          | T
          | {
              about_feature_title_2?: T;
              about_feature_text_2?: T;
            };
        about_feature_3?:
          | T
          | {
              about_feature_title_3?: T;
              about_feature_text_3?: T;
            };
        about_feature_4?:
          | T
          | {
              about_feature_title_4?: T;
              about_feature_text_4?: T;
            };
      };
  about_image?: T;
  about_section?:
    | T
    | {
        about_heading?: T;
        about_paragraphs?:
          | T
          | {
              para_1?: T;
              para_2?: T;
              para_3?: T;
            };
      };
  caroussel_section?:
    | T
    | {
        before?: T;
        after?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  testimonials_section?:
    | T
    | {
        title?: T;
        age?: T;
        text?: T;
        location?: T;
        id?: T;
      };
  services_section?:
    | T
    | {
        title?: T;
        description?: T;
        about_feature_1?:
          | T
          | {
              about_feature_title_1?: T;
              about_feature_text_1?: T;
            };
        about_feature_2?:
          | T
          | {
              about_feature_title_2?: T;
              about_feature_text_2?: T;
            };
        about_feature_3?:
          | T
          | {
              about_feature_title_3?: T;
              about_feature_text_3?: T;
            };
        about_feature_4?:
          | T
          | {
              about_feature_title_4?: T;
              about_feature_text_4?: T;
            };
        about_feature_5?:
          | T
          | {
              about_feature_title_5?: T;
              about_feature_text_5?: T;
            };
        about_feature_6?:
          | T
          | {
              about_feature_title_6?: T;
              about_feature_text_6?: T;
            };
      };
  financial_section?:
    | T
    | {
        title?: T;
        description?: T;
        sub_descrition?: T;
        financial_help_1?:
          | T
          | {
              icon_text?: T;
              title?: T;
              description?: T;
            };
        financial_help_2?:
          | T
          | {
              icon_text?: T;
              title?: T;
              description?: T;
            };
        financial_help_3?:
          | T
          | {
              icon_text?: T;
              title?: T;
              description?: T;
            };
        financial_help_4?:
          | T
          | {
              icon_text?: T;
              title?: T;
              description?: T;
            };
      };
  form_section?:
    | T
    | {
        title?: T;
        description?: T;
        work_zone?:
          | T
          | {
              title?: T;
              region?: T;
              radius?: T;
            };
        time_section?:
          | T
          | {
              title?: T;
              list?:
                | T
                | {
                    devis?: T;
                    travaux?: T;
                    total?: T;
                  };
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?: T | {};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}