onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - '@vercel/speed-insights'
  - esbuild
  - sharp

overrides:
  '@types/react': 19.3.0
  '@types/react-dom': 19.3.0

allowBuilds:
  '@swc/core': true
  '@tailwindcss/oxide': true
  '@vercel/speed-insights': true
  esbuild: true
  sharp: false
