import type { TextCorrection } from "./parityCorrections";

export const cityWordingCorrections: TextCorrection[] = [
  {
    ref: "V1",
    page: "douche-senior-blois",
    from: "Artisan local certifié Handibat & Silverbat. Transformation de votre baignoire en douche plain-pied en 1 journée.",
    to: "Artisan certifié Handibat & Silverbat. Transformation baignoire en douche plain-pied en 1 journée.",
  },
  {
    ref: "V2",
    page: "douche-senior-blois",
    from: "Pourquoi nous faire confiance à Blois ?",
    to: "",
  },
  {
    ref: "V3",
    page: "douche-senior-blois",
    from: "Artisan local Basé à Selles-sur-Cher, intervention rapide sur Blois et toute l'agglo",
    to: "Artisan local Intervention rapide sur Blois et agglo",
  },
  {
    ref: "V4",
    page: "douche-senior-blois",
    from: "Installation 1 jour Le matin baignoire, le soir douche sécurisée utilisable",
    to: "1 journée Installation complète en une journée",
  },
  {
    ref: "V5",
    page: "douche-senior-blois",
    from: "Certifié Handibat Label officiel pour l'adaptation PMR et seniors",
    to: "Certifié Handibat & Silverbat",
  },
  {
    ref: "V6",
    page: "douche-senior-blois",
    from: "Aides financières On vous accompagne pour MaPrimeAdapt et autres aides",
    to: "Aides MaPrimeAdapt",
  },
  {
    ref: "V7",
    page: "douche-senior-blois",
    from: "Intervention sur Blois et toute l'agglomération",
    to: "Zones d'intervention à Blois",
  },
  {
    ref: "V8",
    page: "douche-senior-blois",
    from: "Nous intervenons dans tous les quartiers de Blois et communes environnantes :",
    to: "",
  },
  {
    ref: "V9",
    page: "douche-senior-blois",
    from: "Vous habitez Blois ou l'agglomération ? Demandez votre devis gratuit maintenant. Visite à domicile et réponse sous 24h. Demander un devis gratuit 02 54 97 53 23",
    to: "Vous habitez Blois ? Devis gratuit sous 24h Devis gratuit Appeler",
  },
  {
    ref: "V10",
    page: "douche-senior-bourges",
    from: "Artisan certifié Handibat & Silverbat. Transformation baignoire en douche sécurisée en 1 journée.",
    to: "Artisan certifié Handibat & Silverbat. Transformation baignoire en douche plain-pied en 1 journée.",
  },
  {
    ref: "V11",
    page: "douche-senior-bourges",
    from: "Local Intervention Bourges et environs",
    to: "Artisan local Intervention rapide sur Bourges et agglo",
  },
  {
    ref: "V12",
    page: "douche-senior-bourges",
    from: "Rapide Installation en 1 journée",
    to: "1 journée Installation complète en une journée",
  },
  {
    ref: "V13",
    page: "douche-senior-chateauroux",
    from: "Artisan certifié pour la transformation de votre salle de bain en douche plain-pied sécurisée.",
    to: "Artisan certifié Handibat & Silverbat. Transformation baignoire en douche plain-pied en 1 journée.",
  },
  {
    ref: "V14",
    page: "douche-senior-chateauroux",
    from: "Proximité Intervention sur Châteauroux et environs",
    to: "Artisan local Intervention rapide sur Châteauroux et agglo",
  },
  {
    ref: "V15",
    page: "douche-senior-chateauroux",
    from: "1 jour Installation rapide en 1 journée",
    to: "1 journée Installation complète en une journée",
  },
  {
    ref: "V16",
    page: "douche-senior-chateauroux",
    from: "Aides MaPrimeAdapt disponible",
    to: "Aides MaPrimeAdapt",
  },
  {
    ref: "V17",
    page: "douche-senior-chateauroux",
    from: "Habitant de Châteauroux ? Devis gratuit sous 24h Demander un devis 02 54 97 53 23",
    to: "Vous habitez Châteauroux ? Devis gratuit sous 24h Devis gratuit Appeler",
  },
  {
    ref: "V18",
    page: "douche-senior-orleans",
    from: "Certifié Handibat & Silverbat PMR",
    to: "Certifié Handibat & Silverbat",
  },
  {
    ref: "V19",
    page: "douche-senior-orleans",
    from: "Aides MaPrimeAdapt et autres",
    to: "Aides MaPrimeAdapt",
  },
  {
    ref: "V20",
    page: "douche-senior-orleans",
    from: "Vous habitez Orléans ? Demandez votre devis gratuit. Réponse sous 24h. Devis gratuit Appeler",
    to: "Vous habitez Orléans ? Devis gratuit sous 24h Devis gratuit Appeler",
  },
  {
    ref: "V21",
    page: "douche-senior-romorantin",
    from: "Artisan local basé en Sologne. Transformation de votre baignoire en douche sécurisée en 1 journée.",
    to: "Artisan certifié Handibat & Silverbat. Transformation baignoire en douche plain-pied en 1 journée.",
  },
  {
    ref: "V22",
    page: "douche-senior-romorantin",
    from: "Très local Basé en Sologne, à proximité",
    to: "Artisan local Intervention rapide sur Romorantin et agglo",
  },
  {
    ref: "V23",
    page: "douche-senior-romorantin",
    from: "1 journée Installation ultra-rapide",
    to: "1 journée Installation complète en une journée",
  },
  {
    ref: "V24",
    page: "douche-senior-romorantin",
    from: "Vous habitez Romorantin ou la Sologne ? Devis gratuit sous 24h Devis gratuit Appeler",
    to: "Vous habitez Romorantin ? Devis gratuit sous 24h Devis gratuit Appeler",
  },
  {
    ref: "V25",
    page: "douche-senior-tours",
    from: "Artisan certifié Handibat & Silverbat. Transformation de votre baignoire en douche plain-pied en 1 journée.",
    to: "Artisan certifié Handibat & Silverbat. Transformation baignoire en douche plain-pied en 1 journée.",
  },
  {
    ref: "V26",
    page: "douche-senior-tours",
    from: "Votre artisan de confiance à Tours",
    to: "",
  },
  {
    ref: "V27",
    page: "douche-senior-tours",
    from: "Proximité Intervention rapide sur Tours et toute l'agglomération",
    to: "Artisan local Intervention rapide sur Tours et agglo",
  },
  {
    ref: "V28",
    page: "douche-senior-tours",
    from: "1 journée Installation complète en une seule journée",
    to: "1 journée Installation complète en une journée",
  },
  {
    ref: "V29",
    page: "douche-senior-tours",
    from: "Certifications Handibat & Silverbat pour adaptation PMR",
    to: "Certifié Handibat & Silverbat",
  },
  {
    ref: "V30",
    page: "douche-senior-tours",
    from: "Aides Accompagnement MaPrimeAdapt et autres aides",
    to: "Aides MaPrimeAdapt",
  },
  {
    ref: "V31",
    page: "douche-senior-tours",
    from: "Intervention sur Tours et toute l'agglomération",
    to: "Zones d'intervention à Tours",
  },
  {
    ref: "V32",
    page: "douche-senior-tours",
    from: "Vous habitez Tours ou l'agglomération ? Demandez votre devis gratuit. Réponse sous 24h. Devis gratuit Appeler",
    to: "Vous habitez Tours ? Devis gratuit sous 24h Devis gratuit Appeler",
  },
];
